# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps/arm64/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps/arm64

PRODUCT_COPY_FILES += \
    vendor/gapps/arm64/proprietary/product/lib/libjni_latinimegoogle.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libjni_latinimegoogle.so \
    vendor/gapps/arm64/proprietary/product/lib64/libjni_latinimegoogle.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libjni_latinimegoogle.so

PRODUCT_PACKAGES += \
    GmsCore \
    Phonesky

ifeq ($(TARGET_IS_GROUPER),)
PRODUCT_COPY_FILES += \
    vendor/gapps/arm64/proprietary/product/app/MarkupGoogle/lib/arm64/libsketchology_native.so:$(TARGET_COPY_OUT_PRODUCT)/app/MarkupGoogle/lib/arm64/libsketchology_native.so

PRODUCT_PACKAGES += \
    MarkupGoogle \
    SpeechServicesByGoogle \
    talkback \
    Velvet \
    SetupWizard
endif

$(call inherit-product, vendor/gapps/common/common-vendor.mk)
